name: Release Package # Actions名称
on:
  push: # 监听调用时机为push事件
    branches: ['release'] # 监听 release 分支

jobs:
  ReleaseExpansionPackage:
    runs-on: ubuntu-latest # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    steps:
      - name: pull vuepress-plugin-oh-my-live2d # 步骤名字
        uses: actions/checkout@master # 使用 actions/checkout 库拉取最新源码
        with:
          repository: oh-my-live2d/vuepress-plugin-oh-my-live2d
          token: ${{ secrets.TOKEN }}
      - name: release vuepress-plugin-oh-my-live2d
        run: |
          npm install oh-my-live2d@latest
          git config --global user.name "loclink"
          git config --global user.email "loclink@163.com"

          if [ -n "$(git status -s)" ];then
              version="$(npm view oh-my-live2d version)"
              git add .
              git commit -m "feat: update oh-my-live2d to v$version"
              git push origin master
              export GITHUB_TOKEN=${{ secrets.TOKEN }}
              npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
              npm run release
          fi

        # - name: 项目安装依赖
        #   run: npm install
        # - name: 项目打包构建
        #   run: npm run build
        # - name: 部署产物到服务器
        #   uses: appleboy/scp-action@master
        #   with:
        #     host: ${{ secrets.SSH_HOST }}
        #     username: ${{ secrets.SSH_USERNAME }}
        #     password: ${{ secrets.SSH_PASSWORD }}
        #     source: 'src/.vuepress/dist/'
        #     target: '~/projects/.temp'
        #     rm: true
        #     strip_components: 3

        # - name: 执行远程脚本命令
        #   uses: appleboy/ssh-action@master
        #   with:
        #     host: ${{ secrets.SSH_HOST }}
        #     username: ${{ secrets.SSH_USERNAME }}
        #     password: ${{ secrets.SSH_PASSWORD }}
        #     script: |
        #       rm -rf ~/test
        #       mkdir -p ~/test
        #       cp -rf ~/projects/.temp/*  ~/test/
        # - run: echo "项目部署完成！"
