name: 测试
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: 项目安装依赖
        run: pnpm install --no-frozen-lockfile

      - name: 测试构建
        run: pnpm build

      - name: 测试 Linter
        run: pnpm lint
